### ISSUE TITLE
automatic reconnection

### ISSUE THREAD

**Issue by cfaber** [jareddlc/OpenFit#10]
It seems automatic reconnection may not be fully functional. I'm trying to determine in what cases it fails and will update this once complete.

**Comment by jareddlc** [comment]
I will change behavior of app, and this feature should then be possible

**Comment by cfaber** [comment]
Ah excellent. I think it's going to be required here, as it appears that many operations on the watch result in a disconnect.

**Comment by jareddlc** [comment]
havent experienced this issue
