### ISSUE TITLE
Any method to install apps and set the alarm on Fit?

### ISSUE THREAD

**Issue by XinJiangCN** [jareddlc/OpenFit#14]
thanks to OpenFit I can pair my fit with my non samsung phone, but I find those Gear Fit apps from  Play store cannot be sent to Fit, and suggest I haven't install the GearFit Manager.

Also it seems that OpenFit cannot set alarm(or I didn't find the right way?)

After all, a big THANK YOU for your amazing app. It revitalize my old gear fit! :)

**Comment by jareddlc** [comment]
Currently there is no support for external applications, sorry. Open Fit currently only supports the stock android alarm clock, I would need to figure out the most common alarms to add support for them. thanks

**Comment by XinJiangCN** [comment]
Got it. Thank you! Have a nice day
2015年11月4日 10:05於 "Jared De La Cruz" notifications@github.com寫道：
