### ISSUE TITLE
Feature request: dump data to text file

### ISSUE THREAD

**Issue by cfaber** [jareddlc/OpenFit#15]
Hi,

It would be great if you could dump the workout / pedometer / sleep data to a text file on the device. Doing so would allow you to store your workout data long term without app lock in.

**Comment by jareddlc** [comment]
Good feature! I will see if I can fit this in next updates. However I dont think I will write to file but probably will try to write to google drive. I will test out which method is easier. thanks

**Comment by jareddlc** [comment]
added integration to google fit
