### ISSUE TITLE
Notification icons

### ISSUE THREAD

**Issue by intoinside** [jareddlc/OpenFit#16]
Forget my poor english... icons are not taken from the app that generates notification. It is planned to show correct icon? I'm trying to setup AndroidStudio to see if i can contribute but meanwhile I can send you bt packet for a twitter notification, i have a gear fit and a Google Nexus 4.

**Comment by jareddlc** [comment]
This a a major request, however I dont think I will be able to create this feature, due to to time. If anyone decides to make it I will merge the feature into the app.
