### ISSUE TITLE
Not working with tidal

### ISSUE THREAD

**Issue by nenros** [jareddlc/OpenFit#17]
Next/prev and play/pause is still not working even last update. Song name is displayed properly. Is it any way to fix it? Can i help?

**Comment by jareddlc** [comment]
The way i've implemented the media controller was to see what intent the app expects for prev/next/play/pause. So far i've implemented 2 types:
- Android default audio intents
- Pandoras intents

which means if tidal does not use the default android audio intents, It will not work. What needs to be done is to check if tidal exposes any intents such OpenFit can broadcast the intents and tidal can perform an action.

**Comment by jareddlc** [comment]
closing, no one is implementing
