### ISSUE TITLE
Is possible send notification with icon?

### ISSUE THREAD

**Issue by Tavernari** [jareddlc/OpenFit#19]
Hi,

I installed gear fit manager in my moto and I saw notifications with icons, like messenger from facebook.

I think if the protocol of communication with gear can receive icon from app?

att

**Comment by jareddlc** [comment]
It is possible, I dont think I have plans on doing it myself. But if someone does, I will merge it to master.

**Comment by spino1970** [comment]
Sorry, just asked now in a message... I'm not a developer, but i'm a designer. May I help you for this? How?
