### ISSUE TITLE
Problem with request fitness data

### ISSUE THREAD

**Issue by intoinside** [jareddlc/OpenFit#20]
With this (and previous) release i can't get fitness data, when i tap on it nothing happens. Can be useful a log generated by "adb logcat"?
Also Fit integration didn't work, maybe for fitness data problem...

And also... can't get weather update work...i've never seen in any release..

**Comment by d-braun** [comment]
same here

**Comment by jareddlc** [comment]
Please provide a log, for both fitness and GPS, gps will occure on every hour so you'll have to wait for the cronjob

**Comment by intoinside** [comment]
[logcat.txt](https://github.com/jareddlc/OpenFit/files/63185/logcat.txt)

ABOUT FITNESS DATA AND GOOGLE FIT INTEGRATION
Some update, it worked just one time. I tapped on request fitness data. after few seconds i got it, the tap on sync, then i got a waiting dialog... wait never ends... On fit.google.com i can see only some data uploaded.
Tried many other times, never worked. I hope logcat can help to see what happens.

WEATHER INFO
Logcat contains also weather info. I forgot to enable GPS and now i receive weather notification. Should i see some icon in home screen? I see only time and date.
On weather notification, it is possible to disable vibration?

**Comment by jareddlc** [comment]
based on the log provided, everything seems normal. I see the fitness data in the logs as well as the GPS. Sync can take very long, like 2-4 minutes for the first time (it send 2 weeks of data to google fit), after first sync, it should be only a few seconds. There are many data points that are being uploaded.

Weather seems to be working appropriately as well. It will send a notification and the weather for the clock style.

**Comment by intoinside** [comment]
When i produced that log, no fitness dialog was shown. Do you need some other information?

**Comment by jareddlc** [comment]
sorry you are correct, I was looking at the raw data but it does appear like the fitness isn't being parsed. I will look into what conditions need to be met before parsing. thanks

**Comment by intoinside** [comment]
Don't understand why but now seems to work! Fitness data dialog appears in few seconds and then GoogleFit sync is completed in a couple of minute...
Didn't change anything but seems ok...
