### ISSUE TITLE
Notifications from other programs

### ISSUE THREAD

**Issue by saper-2** [jareddlc/OpenFit#27]
Hi,

I'm using K9 for mail client , and I when I got on watch notification from K9 usually this looks like this:

https://drive.google.com/file/d/0BySjzBz--msUeGpaUUtuMVdfS3c/view?usp=sharing

Very rarely I see a title of K-9 notification (new e-mail subject & date), in most K-9 notifications show up like on photo...

I'll support you work only if you add for K-9 good notifications :wink:

**Comment by jareddlc** [comment]
Notifications implementation is directly using Android NotificationListenerService
