### ISSUE TITLE
OpenFire auto-restart after update

### ISSUE THREAD

**Issue by saper-2** [jareddlc/OpenFit#28]
Hi,

Starting openfit again after each time it update can be really pain in neck :smile: . Most apps auto-restarts itself after update.... I wouldn't have to scroll through my app list to find openfit and open it...

**Comment by etatus** [comment]
+1 An autostart option would be great.

**Comment by jareddlc** [comment]
@rdupuis implemented this feature here: https://github.com/jareddlc/OpenFit/pull/44
