### ISSUE TITLE
Watch language change

### ISSUE THREAD

**Issue by saper-2** [jareddlc/OpenFit#29]
Hi,

I would like to change language on watch, right now it using my native (I think it is because I have updated watch firmware from samsung fit manager installed on my mom Galaxy S4), but I would like to switch to English.
This is just my thing :smile: , I just prefer Eng than my native (I know, I'm odd)

**Comment by jareddlc** [comment]
Currently this is not possible, The raw BT logs, show the language been transferred in a different protocol.

**Comment by outlying** [comment]
+1 for this one

**Comment by Dajb87** [comment]
Kupiłam inny telefon niż samsung. Połączyłam zegarek z telefonem ale mam wszystko po angielsku w telefonie a chciałabym w swoim języku prośbą o pomoc jak to zmienić

**Comment by saper-2** [comment]
> 
> 
> Kupiłam inny telefon niż samsung. Połączyłam zegarek z telefonem ale mam wszystko po angielsku w telefonie a chciałabym w swoim języku prośbą o pomoc jak to zmienić

This is 5y old issue. Ask for help on some android group instead.
