### ISSUE TITLE
Hide OpenFit icon from statusbar

### ISSUE THREAD

**Issue by limerainne** [jareddlc/OpenFit#46]
It'll be good if OpenFit notification icon is hidden from statusbar and just notification message is shown in notification list.

Just adding below line in **OpenFitService.java:createNotification()** will do the job:
`nBuilder.setPriority(NotificationCompat.PRIORITY_MIN);`

I've been tested above code without experiencing unexpected OpenFit service termination, but it could harm the stability of OpenFitService...

**Comment by jareddlc** [comment]
I'm unsure if this is the behavior people would like given that it has been released for a while with the icon on the statusbar.
