### ISSUE TITLE
Notifications broken on version 1.9.1

### ISSUE THREAD

**Issue by linuxct** [jareddlc/OpenFit#48]
The notification system is totally broken on version 1.9.1, tested on a Sony Xperia M2 running Android 4.4.4. I've disabled and re-enabled notification access, but still refuses to work. In the application itself, it clearly says there are no apps added to the notification apps list, however there are several already. You can have a look in the screenshot attached. 

![screenshot_2016-10-04-14-23-07](https://cloud.githubusercontent.com/assets/3966313/19081372/4af289b2-8a5a-11e6-87b9-32784075b984.png)

**Comment by jareddlc** [comment]
are you by any chance rooted?

**Comment by linuxct** [comment]
@jareddlc Not at the moment, but I can root it if needed

**Comment by jareddlc** [comment]
@sergiocastell I will need access to the logs to determine what the issue is. I'm on 6.0.1 and notifications where working fine.  Ive listed how to get logs if you are rooted:

http://forum.xda-developers.com/gear-fit/themes-apps/openfit-source-gear-fit-application-t3005697

You are also able to get logs, if you have android studio installed and connect the phone in debug mode. I just think that might be more complicated, but no root necessary.

**Comment by jareddlc** [comment]
A user was kind enough to send me a small log. It looks like it could have possibly have an issue with the new way for notifications. here: https://github.com/jareddlc/OpenFit/blob/master/app/src/main/java/com/solderbyte/openfit/NotificationService.java#L331 

I wonder if this doesnt work for andorid 4.4.4 as it was reported on 4.4.4

**Comment by linuxct** [comment]
Does Google Play Developer Console let you check the Android OS version of the people who left you a review in the Play Store? Because if so, I've seen 2 or 3 comments that do describe my exact same issue, but I can't see what OS version they have. Also, I'll try once I arrive home with an Android 5.1.1 device, to see if that changes or not.

**Comment by jareddlc** [comment]
It does, it shows a few comments as 4.4 and one of 5.1 and another of 6. However I think the 5.1 and 6 maybe a different issue. Would it be possible to provide with more logs. I only got 1 line. and based on thee log you send. One notification was filtered because it wasn't added to the list. However it is known that WhatsApp emits two notifications. Thanks

**Comment by jareddlc** [comment]
@sergiocastell have you tried restarting your phone?

https://code.google.com/p/android/issues/detail?id=62811

**Comment by jareddlc** [comment]
I think I will try this method. To force the notification service listener

http://stackoverflow.com/a/38636227/1657579

**Comment by linuxct** [comment]
I've finally managed to give it a try on my own device, which is also a Xperia M2 but running on Android 5.1.1. The issue still happened, on WhatsApp and Telegram as far as I tested, since I was receiving Newton Mail notifications (twice, btw). All 3 mentioned apps were in the Notification listener list. Now, I need to try again on Android 4.4, but my guess is that the same thing will happen. 

I've attached a log for you, if you see some Bluetooth crashing please ignore it, it may be related with the ROM I'm currently running on. 

[Log_2016-10-05_18-47-21.txt](https://github.com/jareddlc/OpenFit/files/511797/Log_2016-10-05_18-47-21.txt)

*edit: Newer logs
*edit 2: Tested on Android 4.4, the same issue happens, Newton Mail notifications arrive twice, but Telegram and WhatsApp do not even appear. Any ideas, @jareddlc?

**Comment by jareddlc** [comment]
Thanks @sergiocastell  Another user sent in logs, with the exact issue as yours. I think I maybe able to solve this soon. Update soon

**Comment by linuxct** [comment]
Nice one @jareddlc, it's been fixed, working on both Android 4.4 and 5.1. Congrats for the nice app!

Still, my father would like to note that the "No applications added, hit the + button to add..." message is still there, appearing even though there are apps already added, and that are perfectly working in here. It's a minor bug, but would love to see that fixed too if possible.
