### ISSUE TITLE
OpenFit and Android 8.1

### ISSUE THREAD

**Issue by javajeb** [jareddlc/OpenFit#51]
We have a Pixel that had OpenFit connected to a Gear Fit. Once the Android 8.1 update came down, the Gear Fit notifications were all in a Asian script (Chinese maybe?). I've looked through the settings of the OpenFit application, the device, stopped OpenFit, cleared data/cache to no effect. Was going to reinstall, but it's gone from the PlayStore, which leads me to believe it may be a dead project.

Any confirmation/help?

Thanks,
kj4ufp

**Comment by jareddlc** [comment]
hey @javajeb OpenFit parses the text from the received notifications, it does not not assume any language. Google removed OpenFit from the google play store due to the app not having a privacy policy, and once i get some time i'll be updating the app to include it. Shortly after i may be releasing a new version of OpenFit that refactors code and updates the UI of the application.

**Comment by javajeb** [comment]
The only change I'm aware of in the phone was the update to Android 8.1. Notifications on the phone screen are in English. 

Something else we may look at to solve this? Heard of it before?

**Comment by psteller** [comment]
I updated my phone from 8.0 to 8.1 yesterday and am seeing the same behavior. Notifications delivered via OpenFit are in non-English characters.
![img_20180109_153735](https://user-images.githubusercontent.com/35277512/34747017-a285a492-f553-11e7-9c63-883b53ede232.jpg)

**Comment by jareddlc** [comment]
@psteller  thanks, i'll look into this. I'll be starting the rewrite of OpenFit and will address this issue

**Comment by Zitti** [comment]
I know there are just a few people who  want a functionable OpenFit back, but the connection issue,  the asian characters and the not updating weather make the app not usable. So im glad to hear, that you ll rewrite the app :)

**Comment by jareddlc** [comment]
fixed in #57
