### ISSUE TITLE
Breaking connection

### ISSUE THREAD

**Issue by saper-2** [jareddlc/OpenFit#52]
Hi,

About 2 updates ago of OpenFit my GF started to disconnect and connect at random (this is freaking annoying when it vibrating for no reason), sometime is once, twice or even few time at row - which usually ends with OpenFit application permanently closed - so I have to go to Apps and launch OpenFit manually...
Also I noticed from time-to-time some settings are lost, especially (most annoying for me) clock format revert to 12h.
Everything was fine before... My phone is: huawei P10 with android 7.0  & EMUI 5.1 ...

**Comment by jareddlc** [comment]
I'm not sure about the disconnect issue, but I will try to improve the behavior of saved settings such that, when reconnecting it applies the user specified setting (clock format, etc) I'll get this done with the rewrite

**Comment by saper-2** [comment]
Hello, I'm sorry for late answer, but the problem was a huawei - after recent bigger os update the issue has gone. There had to be a small update from huawei and it had to overlap with a update of Openfit . So, I must had forgotten about it...
