### ISSUE TITLE
Logo design

### ISSUE THREAD

**Issue by neemanbhat** [jareddlc/OpenFit#55]
Hi, I will like to design a new logo for this gear fit manager if you allow me to. I will take care of the requirements if specified. Please comment below and let me know.

**Comment by jareddlc** [comment]
I had designed this while I was thinking of the new OpenFit version. This is a sketch and open to discussion.

![openfit](https://user-images.githubusercontent.com/1082238/39645443-2a7ab0c0-4f8d-11e8-8b88-1b3ce86b4016.jpg)

**Comment by neemanbhat** [comment]
Internet is down for few days i will get back to you ASAP.

**Comment by debpedrano** [comment]
@jareddlc 
how about this ? 
![image](https://user-images.githubusercontent.com/40510200/42121124-34e769c2-7c5b-11e8-9926-964a83dfc573.png)

**Comment by debpedrano** [comment]
how about this one @jareddlc  ?
![image](https://user-images.githubusercontent.com/40510200/42121126-4efbb732-7c5b-11e8-8085-c5cd1e5a8399.png)

**Comment by debpedrano** [comment]
@jareddlc  issue [link](https://github.com/jareddlc/OpenFit/issues/59)

**Comment by jareddlc** [comment]
@debpedrano great work! You got the essence of what I wanted from my sketch. There are some changes I would like to see, and i'll try my best to describe them.

1. The curves from the wrist band and the screen dont quite match. The screen is rounded while the wrist band is sharp. I would like to see the screen the screen part not be too rounded and same with the inner screen.
2. I'm not sure what should go inside the screen, if it should be blank and a text "OpenFit" below. Im not sure yet.

I would like this to be an open discussion, so if you have questions to ask please feel free. thanks

**Comment by debpedrano** [comment]
I will make some changes on it @jareddlc
