### ISSUE TITLE
Gear fit connect failed

### ISSUE THREAD

**Issue by Jake1702** [jareddlc/OpenFit#56]
No matter how many times I try to connect, it always fails. It's getting a bit annoying at this point because obviously the gear fit is unusable without pairing.

**Comment by rdupuis** [comment]
Hello Jake,
Have you tried the procedure described in the help?

> **Connection Problems:**
        If you cannot pair with Gear Fit from Open Fit application,
        go to bluetooth settings, and remove the Gear Fit from the list of paired devices,
        then scan and pair to the Gear Fit via the Open Fit app.
        **Note:** You may need to reset the Gear Fit.

**Comment by bertin0** [comment]
For me on android p it still doesn't work. I tried to reset the watch many times, reinstalled the app and still can't get it to work.

**Comment by e-t-l** [comment]
I also cannot connect the app to my gear fit, even after following the instructions above.
