### ISSUE TITLE
Logo Enhancement

### ISSUE THREAD

**Issue by debpedrano** [jareddlc/OpenFit#59]
Greetings PO,

If you have any ideas about logo, you can contact me or directly comment. I can make on that fits on your Project.

**Comment by jareddlc** [comment]
see #55

**Comment by debpedrano** [comment]
@jareddlc 
hello PO
![image](https://user-images.githubusercontent.com/40510200/42121127-59a1f7dc-7c5b-11e8-9144-b95459157142.png)
