### ISSUE TITLE
OpenFit 2.0 support for Galaxy Fit

### ISSUE THREAD

**Issue by siccovansas** [jareddlc/OpenFit#67]
Hi :)

I was wondering if OpenFit 2.0 is still in the works? I got a Galaxy Fit for free with a phone recently and only want to used it without closed source/private-cloud-based apps. It would be awesome if OpenFit 2.0 got released and if it supports Galaxy Fit.

OpenFit has (had?) many many users, so it would be great if a new release became available. I'd definitely pay/donate for it :+1:

**Comment by jareddlc** [comment]
Thanks. I haven't worked much on 2.0 app, i have got work done to rewrite the bluetooth stack, however its been a while since my last commit (Mar 9, 2019). I would like to get back to this project. closing and adding in in #47
