### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by e-t-l** [jareddlc/OpenFit#68]
I'm not able to connect my Gear Fit 2 (SM-R360) to my Android 11 device using Open Fit v1.12.0. I had it connected to my phone using the Samsung Wearables app, but was less than impressed with Samsung's functionality, so I disconnected it from the Wearables app, Forgot the bluetooth connection from my phone, and tried to connect it via Open Fit, but it just keeps saying connection failed.

**Comment by e-t-l** [comment]
I factory-reset my Fit 2, scanned for it in Open Fit, found it, but it still says connection failed.

**Comment by jareddlc** [comment]
this is for the original gear fit, gear fit 2 isn't supported.
