### ISSUE TITLE
Any chance to move this project to Android Studio and use Gradle ?

### ISSUE THREAD

**Issue by outlying** [jareddlc/OpenFit#7]
It would be easier to contribute to this project, current setup seems like Eclipse, which is at best ancient and active support for Android plugin for Eclipse has ended http://android-developers.blogspot.com/2015/06/an-update-on-eclipse-android-developer.html

**Comment by jareddlc** [comment]
I have thought of changing, and maybe next month or so, I'll look into android studio

**Comment by outlying** [comment]
Thanks, I would be happy to support this project from time to time

**Comment by jareddlc** [comment]
Always welcome to do so. Ive been running behind, especially since i was trying to get fitness data. Now i can focus on fixing some bugs

**Comment by outlying** [comment]
I would gladly do that but this will force you to change your IDE and other stuff, but if it's OK I may do that, just give tell me when would be the right moment, so it wouldn't interference with any of your current work

**Comment by jareddlc** [comment]
okay, I have a few things I would like to fix, refactor, and change, and after that It should be good to do a change over.

**Comment by jareddlc** [comment]
I think I have 2 more updates left. Im not sure if it will be worth moving over to android studio, but I will not be opposed at all. After these last few features I dont think I will be adding more features and just mainly do support.

**Comment by outlying** [comment]
Thanks, since I'm on holidays I won't be able to do this myself till middle
of December

Niedz., 22 lis 2015, 02:35 Jared De La Cruz użytkownik <
notifications@github.com> napisał:

**Comment by jareddlc** [comment]
moved to android studio
